/**
 * EnhancedAnalysisPage.js - Comprehensive TOR Analysis Dashboard
 * Tamil Nadu Police Cyber Crime Wing - TOR-Unveil
 * 
 * Integrates all analysis components: network topology, timeline, origin identification, etc.
 */

import React, { useState, useEffect } from "react";
import axios from "axios";
import { useNavigate, useLocation } from "react-router-dom";
import TorNetworkTopology from "./components/TorNetworkTopology";
import TrafficTimeline from "./components/TrafficTimeline";
import OriginIdentificationDashboard from "./components/OriginIdentificationDashboard";
import { exportReportAsPDF, exportDataAsCSV, exportAsJSON } from "./utils/ForensicReportExporter";
import "./EnhancedAnalysisPage.css";

const API_URL = process.env.REACT_APP_API_URL || "http://127.0.0.1:8000";

export default function EnhancedAnalysisPage() {
  const navigate = useNavigate();
  const location = useLocation();

  const searchParams = new URLSearchParams(location.search);
  const caseId = searchParams.get('caseId') || location.state?.caseId || "TN/CYB/2024/001234";

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [caseData, setCaseData] = useState(null);
  const [analysisData, setAnalysisData] = useState(null);
  const [originData, setOriginData] = useState(null);
  const [activeTab, setActiveTab] = useState('overview');
  const [exporting, setExporting] = useState(false);

  // Fetch all analysis data
  useEffect(() => {
    const fetchAllData = async () => {
      try {
        setLoading(true);
        setError(null);

        // Fetch case data
        const caseResponse = await axios.get(
          `${API_URL}/api/investigations/${encodeURIComponent(caseId)}`
        );
        setCaseData(caseResponse.data);

        // Fetch analysis data
        const analysisResponse = await axios.get(
          `${API_URL}/api/analysis/${encodeURIComponent(caseId)}`
        );
        setAnalysisData(analysisResponse.data);

        // Fetch origin identification data
        const originResponse = await axios.get(
          `${API_URL}/api/analysis/${encodeURIComponent(caseId)}/origin-identification`
        );
        setOriginData(originResponse.data.origins || []);
      } catch (err) {
        console.warn('Using demo analysis data:', err.message);
        // Demo data will be generated by individual components
      } finally {
        setLoading(false);
      }
    };

    fetchAllData();
  }, [caseId]);

  // Handle PDF export
  const handleExportPDF = async () => {
    try {
      setExporting(true);
      const result = exportReportAsPDF(caseData, analysisData, originData);
      if (result.success) {
        alert(`Report exported successfully: ${result.filename}`);
      }
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('Failed to export PDF report');
    } finally {
      setExporting(false);
    }
  };

  // Handle CSV export
  const handleExportCSV = async (type) => {
    try {
      setExporting(true);
      const result = exportDataAsCSV(originData, analysisData, type);
      if (result.success) {
        alert(`Data exported successfully: ${result.filename}`);
      }
    } catch (err) {
      console.error('CSV export failed:', err);
      alert('Failed to export CSV data');
    } finally {
      setExporting(false);
    }
  };

  // Handle JSON export
  const handleExportJSON = async () => {
    try {
      setExporting(true);
      const result = exportAsJSON(caseData, analysisData, originData);
      if (result.success) {
        alert(`Data exported successfully: ${result.filename}`);
      }
    } catch (err) {
      console.error('JSON export failed:', err);
      alert('Failed to export JSON data');
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="enhanced-analysis-page">
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Loading comprehensive analysis dashboard...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="enhanced-analysis-page">
        <div className="error-state">
          <p className="error-message">⚠️ {error}</p>
          <button onClick={() => navigate('/investigation')} className="btn-back">
            Back to Investigation
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="enhanced-analysis-page">
      {/* Header */}
      <div className="page-header">
        <div className="header-content">
          <h1>TOR Correlation Analysis</h1>
          <p className="case-reference">Case: {caseId}</p>
        </div>
        <div className="header-actions">
          <button
            className="btn-export-menu"
            disabled={exporting}
            onClick={() => {}}
            title="Export analysis data"
          >
            📥 Export
          </button>
          <div className="export-dropdown">
            <button className="export-btn" onClick={handleExportPDF} disabled={exporting}>
              📄 Export PDF Report
            </button>
            <button className="export-btn" onClick={() => handleExportCSV('origins')} disabled={exporting}>
              📊 Export Origins (CSV)
            </button>
            <button className="export-btn" onClick={() => handleExportCSV('hypotheses')} disabled={exporting}>
              📊 Export Hypotheses (CSV)
            </button>
            <button className="export-btn" onClick={handleExportJSON} disabled={exporting}>
              📋 Export All (JSON)
            </button>
          </div>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="tab-navigation">
        <button
          className={`tab-btn ${activeTab === 'overview' ? 'active' : ''}`}
          onClick={() => setActiveTab('overview')}
        >
          📊 Overview
        </button>
        <button
          className={`tab-btn ${activeTab === 'topology' ? 'active' : ''}`}
          onClick={() => setActiveTab('topology')}
        >
          🔗 Network Topology
        </button>
        <button
          className={`tab-btn ${activeTab === 'timeline' ? 'active' : ''}`}
          onClick={() => setActiveTab('timeline')}
        >
          ⏰ Timeline
        </button>
        <button
          className={`tab-btn ${activeTab === 'origins' ? 'active' : ''}`}
          onClick={() => setActiveTab('origins')}
        >
          🎯 Origin Identification
        </button>
        <button
          className={`tab-btn ${activeTab === 'forensic' ? 'active' : ''}`}
          onClick={() => setActiveTab('forensic')}
        >
          🔍 Forensic Details
        </button>
      </div>

      {/* Tab Content */}
      <div className="tab-content">
        {/* Overview Tab */}
        {activeTab === 'overview' && (
          <div className="tab-pane active">
            <div className="overview-grid">
              <div className="overview-card">
                <h3>Analysis Status</h3>
                <div className="status-info">
                  <span className="status-badge completed">✓ Completed</span>
                  <p>All correlation analyses have been processed successfully.</p>
                </div>
              </div>

              <div className="overview-card">
                <h3>Key Metrics</h3>
                <div className="metrics-list">
                  <div className="metric">
                    <span className="metric-label">Total Hypotheses:</span>
                    <span className="metric-value">{analysisData?.hypotheses?.length || 0}</span>
                  </div>
                  <div className="metric">
                    <span className="metric-label">Origin IPs Identified:</span>
                    <span className="metric-value">{originData?.length || 0}</span>
                  </div>
                  <div className="metric">
                    <span className="metric-label">Primary Confidence:</span>
                    <span className="metric-value confidence">
                      {originData && originData.length > 0 
                        ? `${(originData[0].confidence_score * 100).toFixed(1)}%`
                        : 'N/A'}
                    </span>
                  </div>
                </div>
              </div>

              <div className="overview-card">
                <h3>Quick Summary</h3>
                <div className="summary-text">
                  <p>
                    The analysis has identified <strong>{originData?.length || 0} potential origin IPs</strong> through 
                    probabilistic correlation of TOR network metadata. The primary hypothesis suggests an origin in 
                    <strong> {originData && originData.length > 0 ? ` ${originData[0].region}, ${originData[0].country}` : ' Unknown'}</strong> 
                    with high confidence based on timing analysis, session overlap, and network behavior patterns.
                  </p>
                </div>
              </div>
            </div>

            <div className="disclaimer-section">
              <h4>⚠️ Important Notice</h4>
              <p>
                This analysis presents probabilistic forensic hypotheses only. All conclusions require independent 
                verification through lawful investigative channels. The confidence scores represent statistical similarity, 
                not definitive identification.
              </p>
            </div>
          </div>
        )}

        {/* Network Topology Tab */}
        {activeTab === 'topology' && (
          <div className="tab-pane active">
            <TorNetworkTopology caseId={caseId} hypothesis={analysisData?.hypotheses?.[0]} />
          </div>
        )}

        {/* Timeline Tab */}
        {activeTab === 'timeline' && (
          <div className="tab-pane active">
            <TrafficTimeline caseId={caseId} />
          </div>
        )}

        {/* Origin Identification Tab */}
        {activeTab === 'origins' && (
          <div className="tab-pane active">
            <OriginIdentificationDashboard caseId={caseId} />
          </div>
        )}

        {/* Forensic Details Tab */}
        {activeTab === 'forensic' && (
          <div className="tab-pane active">
            <div className="forensic-details">
              <h3>Detailed Forensic Analysis</h3>
              
              {analysisData?.hypotheses && analysisData.hypotheses.length > 0 && (
                <div className="hypotheses-section">
                  <h4>Ranked Hypotheses</h4>
                  <div className="hypotheses-list">
                    {analysisData.hypotheses.map((hypothesis, idx) => (
                      <div key={idx} className="hypothesis-item">
                        <div className="hypothesis-header">
                          <span className="rank">#{hypothesis.rank}</span>
                          <span className="path">
                            {hypothesis.entry_region} → {hypothesis.exit_region}
                          </span>
                          <span className={`confidence-badge ${hypothesis.confidence_level.toLowerCase()}`}>
                            {hypothesis.confidence_level}
                          </span>
                        </div>
                        <div className="hypothesis-content">
                          <p><strong>Timing Correlation:</strong> {hypothesis.timing_correlation}</p>
                          <p><strong>Session Overlap:</strong> {hypothesis.session_overlap}</p>
                          <p><strong>Evidence Consistency:</strong> {hypothesis.evidence_consistency}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="page-actions">
        <button className="btn-secondary" onClick={() => navigate('/investigation')}>
          ← Back to Investigation
        </button>
        <button className="btn-primary" onClick={() => navigate('/report')}>
          View Detailed Report →
        </button>
      </div>
    </div>
  );
}
